### ISSUE TITLE
turn wikipedia links into iframes

### ISSUE THREAD

**Issue by jesserayn** [mlava/shortcode-embeds#1]
https://en.wikipedia.org/wiki/David_Deutsch
->
{{iframe: https://en.wikipedia.org/wiki/David_Deutsch}}
I use the .m for mobile for a cleaner reading experience.
{{iframe: https://en.m.wikipedia.org/wiki/David_Deutsch}}
<img width="775" alt="Screenshot 2023-03-28 at 5 28 22 PM" src="https://user-images.githubusercontent.com/57831376/228396045-32a9f99e-a72f-47fa-99f6-27071627fad7.png">

**Comment by mlava** [comment]
Hi @jesserayn Sorry for the delay in reply.
I don't think everyone will want this automatically, but am happy to make it configurable in settings.
You would need to 'opt-in' in settings and then we can do this.
Ok?

**Comment by jesserayn** [comment]
That would make my week!

**Comment by mlava** [comment]
Hi again.
I've submitted a PR, so once the RR guys review and accept you should start getting the mobile version instead of the original.
https://github.com/Roam-Research/roam-depot/pull/659
Cheers!
