### ISSUE TITLE
[feature request] is it possible to embed instagram in roam?

### ISSUE THREAD

**Issue by bleedingsaber** [mlava/shortcode-embeds#2]
I found a way to embed tiktok in roam in [ob forum](https://forum.obsidian.md/t/tiktok-embed-autoplay-off/84056), but can not find a way to embed instagram. do you have any tricks to do this?

**Comment by mlava** [comment]
I've just pushed an update that matches both Instagram and TikTok and converts to appropriate code.
You just need to wait for the RR guys to review and approve.
Thanks for the good idea!

**Comment by mlava** [comment]
https://github.com/Roam-Research/roam-depot/pull/920

**Comment by bleedingsaber** [comment]
thanks for your quick reply, you are amazing!!
